### ISSUE TITLE
请问networks是如何生成的？

### ISSUE THREAD

**Issue by bluueskyer** [ChenBaiyang/MAUIL#4]
作者大大您好，我也在研究社交网络中的用户对齐问题，在运行您的代码，但是有一个小小的疑惑就是networks是如何生成的呢，它存储的是什么内容呢~希望能得到您的解答！谢谢

**Comment by ChenBaiyang** [comment]
您好！
社交网络在编程中体现为一个属性图（Attributed graph/network）的数据结构。具体而言，一个用户表示为图中的一个顶点（代码中一般体现为一个整型的ID）,用户之间的一个关系表示为图中一条边（代码中一般体现为一对用户的ID，也可以用图的邻接矩阵表示），用户的属性（如名字、性别等）表示为一系列键值对（如“性别：男”，代码中则直接存储相应的属性值）。而网络的生成过程则可以看做是把相应的顶点、边、属性键值对逐一添加到网络中的一些列步骤。这些操作有多种工具可以借用，比如python的networkx、graph_tool等。

如有其它问题，欢迎一起交流。

谢谢！

**Comment by bluueskyer** [comment]
您有生成networks的代码嘛~我就是很想知道您networks的具体设计呢~谢谢您的回复~
