### ISSUE TITLE
无法重现

### ISSUE THREAD

**Issue by ReceiveWind** [ChenBaiyang/MAUIL#5]
作者您好，下载您的代码后一直没有办法重现，dblp可以获得嵌入，但是wd一直出问题，不知是否方便问一下，
我在网上下载好了zhwiki-latest-pages-articles.xml这个文件，大概两个G,
运行嵌入的代码就一直报错RuntimeError: you must first build vocabulary before training the model，而且会生成一个o kb的zhwiki_corpus文件，在网上查了说是word2vec的时候min_count问题，试过了没有解决
尝试在网上找其他的代码生成zhwiki_corpus，但是再次运行嵌入的代码会卡在Learning word vectors不动了，一晚上也没有反应，不知道您是否遇到过？放不方便解答下疑问么？

**Comment by ChenBaiyang** [comment]
您好！
非常感谢您对我们工作的关注。您提到的问题实质上都是中文词语料预训练的问题：
（1）wiki中文预料库一直有在更新，相关软件模块也有变化，因此可能需要对代码进行一些调整。
（2）“生成一个o kb的zhwiki_corpus文件”说明词向量训练不成功，原因还是在wiki预料库的预处理模块上，和word2vec无关。
（3）Learning word vectors 是直接调用的gensim模块，可以结合cpu运行状态来分析原因。
（4）我已经将处理好的wiki语料文件zhwiki_corpus上传到网盘，您可以直接下载，从而跳过wiki语料的预处理步骤。下载地址： 
 https://share.weiyun.com/mOpp4cLv 

如有其它问题，欢迎一起交流。

谢谢！

**Comment by ReceiveWind** [comment]
好的，我再试试，真的非常感谢您的帮助，谢谢
